//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreAPI.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookReview
    {
        public int ReviewId { get; set; }
        public string ReviewText { get; set; }
        public string Rating { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public int BookId { get; set; }
        public string ReviewerName { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
